version: '2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./app.env
    volumes:
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./app.env

  labeling-app:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - labeling-api

  labeling-api:
    build: ./backend
    env_file:
      - ./app.env
    ports:
      - 4000:4000
    depends_on:
      - mongo
