version: '2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./app.env
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./app.env